name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HUGGINGFACE: ${{ secrets.HUGGINGFACE }}
        # run: git remote add space https://noahgift:$HUGGINGFACE@huggingface.co/spaces/noahgift/demo
        run: git remote add space https://Sogodam:$HUGGINGFACE@huggingface.co/spaces/Sogodam/demo
      - name: Push to hub
        env:
          HUGGINGFACE: ${{ secrets.HUGGINGFACE }}
        # run: git push --force https://noahgift:$HUGGINGFACE@huggingface.co/spaces/noahgift/demo main
        run: git push --force https://Sogodam:$HUGGINGFACE@huggingface.co/spaces/Sogodam/demo main
